version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api.insecure=true # Don't do that in production
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: whoami_1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.rule=Host(`whoami1.localhost`)"
      - "traefik.http.routers.whoami1.entrypoints=web"
      # Middleware para comprimir paginas.
      - traefik.http.middlewares.compress.compress=true

  whoami2:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: whoami_2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.rule=Host(`whoami2.localhost`)"
      - "traefik.http.routers.whoami2.entrypoints=web"
      # Middleware para comprimir paginas.
      - traefik.http.middlewares.compress.compress=true
