version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --entrypoints.websecure.address=:443  # Agregamos el punto de entrada websecure
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true # Don't do that in production
      - --log.level=DEBUG

      - --certificatesresolvers.myresolver.acme.tlschallenge=true
#     - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.email=jorge.obiols@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/opt/traefik/acme.json
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /odoo_ar/traefik/:/opt/traefik/

  whoami1:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: whoami_1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.rule=Host(`prod-monaco.ddns.net`)"
      - "traefik.http.routers.whoami1.entrypoints=websecure"
      - "traefik.http.routers.whoami1.tls.certresolver=myresolver"

      # Middleware para comprimir paginas.
      #- traefik.http.middlewares.compress.compress=true

  whoami2:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: whoami_2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.rule=Host(`test-monaco.ddns.net`)"
      - "traefik.http.routers.whoami2.entrypoints=websecure"
      - "traefik.http.routers.whoami2.tls.certresolver=myresolver"

      # Middleware para comprimir paginas.
      #- traefik.http.middlewares.compress.compress=true
